name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build and push Docker image
        run: |
          docker build -t dashboard-backend .
          docker tag dashboard-backend:latest ${{ secrets.DOCKER_REPO_URL }}/dashboard-backend:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_REPO_URL }}/dashboard-backend:latest

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.MY_EC2_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_REPO_URL }}/dashboard-backend:latest
            docker stop dashboard-backend || true
            docker rm dashboard-backend || true
            docker run -d -p 3333:3333 --name dashboard-backend ${{ secrets.DOCKER_REPO_URL }}/dashboard-backend:latest